### ISSUE TITLE
Memory leak when using marshaler

### ISSUE THREAD

**Issue by Oted** [CascadeEnergy/dynamoDb-marshaler#11] opened 2015-09-24 15:50 UTC
I currently have some tests set up for my project which uses the marshaller.

The tests are run with https://github.com/hapijs/lab which detects memory leaks. When this project is required anywhere in the code i get the following warning at the end : 

`The following leaks were detected:__core-js_shared__`

Don't know where this happens in the code but it's certainly coming from this module.

**Comment by nackjicholson** [comment] 2015-09-24 16:08
Thanks for the report. If you can give me any further information, that would be helpful. I honestly have no idea where to even start to diagnose the problem or even confirm that there is one.

**Comment by Josiah** [comment] 2015-11-06 12:45
I stumbled across this issue while googling `__core-js_shared__` - this is indeed a babel thing related to the core-js library. I've not got any more details than this unfortunately.

**Comment by nackjicholson** [comment] 2015-11-06 17:17
@Josiah Thanks for looking into that for me, that was my suspicion. If you have any links where you found that it would be appreciated. I will likely upgrade my dependencies on babel and hope the issue is resolved by that. Been meaning to get around to doing that and keep putting it off :)

**Closed** 2015-11-06 18:24 UTC
